<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Location Maisons</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      background-color: #f8f8f8;
    }
    header {
      background-color: #2c3e50;
      color: white;
      padding: 20px;
      text-align: center;
    }
    .container {
      padding: 20px;
    }
    .house {
      background-color: white;
      margin-bottom: 20px;
      padding: 15px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }
    .house img {
      width: 100%;
      border-radius: 5px;
    }
    .house h2 {
      margin-top: 10px;
    }
    .house p {
      margin: 5px 0;
    }
  </style>
</head>
<body>
  <header>
    <h1>Location de Maisons</h1>
    <p>Trouvez la maison idéale pour vos vacances</p>
  </header>
  <div class="container">
    <div class="house">
      <img src="https://via.placeholder.com/600x300" alt="Maison 1">
      <h2>Maison en Provence</h2>
      <p><strong>Prix :</strong> 120€/nuit</p>
      <p><strong>Chambres :</strong> 3</p>
      <p><strong>Description :</strong> Charmante maison avec jardin et piscine, idéale pour une famille.</p>
    </div>

    <div class="house">
      <img src="https://via.placeholder.com/600x300" alt="Maison 2">
      <h2>Villa en Bretagne</h2>
      <p><strong>Prix :</strong> 90€/nuit</p>
      <p><strong>Chambres :</strong> 2</p>
      <p><strong>Description :</strong> Vue sur mer, terrasse et accès direct à la plage.</p>
    </div>
  </div>
</body>
</html>
